# Root project (harus di folder yang ada go.mod & main.go)
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ./cmd/web"


  # Ekstensi file yang dipantau
  include_ext = ["go", "tpl", "tmpl", "html", "env", "json", "yaml", "yml"]

  # Folder yang diabaikan
  exclude_dir = ["tmp", "vendor", "testdata"]

  # File test tidak dipantau
  exclude_regex = ["_test.go"]

  # Agar selalu rebuild walau perubahan kecil
  exclude_unchanged = false

  # Mode polling untuk Windows biar stabil
  poll = true
  poll_interval = 500

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
