services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./app.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    command: -p 5433
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ngabaca_go
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
